development:
  adapter: postgresql
  encoding: unicode
  database: quakismart_bootstrap_development
  pool: 5  
  password:  
test:
  adapter: postgresql
  encoding: unicode
  database: quakismart_bootstrap_test
  pool: 5 
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: quakismart_bootstrap_production
  pool: 5 
  password: